# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v1/cloud_provider.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "gpcore/api/cloud/v1/cloud_provider.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gpcore_sdk.gpcore.type.v1 import (
    cloud_provider_pb2 as gpcore_dot_type_dot_v1_dot_cloud__provider__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n(gpcore/api/cloud/v1/cloud_provider.proto\x12\x13gpcore.api.cloud.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#gpcore/type/v1/cloud_provider.proto"C\n\x16\x43loudProviderInterface\x12\x13\n\x0bmac_address\x18\x01 \x01(\t\x12\x14\n\x0cip_addresses\x18\x02 \x03(\t"\xf9\x01\n\x15\x43loudProviderResource\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12?\n\ninterfaces\x18\x04 \x03(\x0b\x32+.gpcore.api.cloud.v1.CloudProviderInterface\x12\x14\n\x07node_id\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tpermalink\x18\x06 \x01(\tH\x01\x88\x01\x01\x12/\n\ncreated_at\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\n\n\x08_node_idB\x0c\n\n_permalink"\xd4\x01\n\x12\x43loudProviderImage\x12\n\n\x02id\x18\x01 \x01(\t\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.gpcore.type.v1.CloudProviderType\x12\x1f\n\x17\x63loud_provider_image_id\x18\x03 \x01(\t\x12/\n\ncreated_at\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\nupdated_at\x18\xe9\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v1.cloud_provider_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CLOUDPROVIDERINTERFACE"]._serialized_start = 135
    _globals["_CLOUDPROVIDERINTERFACE"]._serialized_end = 202
    _globals["_CLOUDPROVIDERRESOURCE"]._serialized_start = 205
    _globals["_CLOUDPROVIDERRESOURCE"]._serialized_end = 454
    _globals["_CLOUDPROVIDERIMAGE"]._serialized_start = 457
    _globals["_CLOUDPROVIDERIMAGE"]._serialized_end = 669
# @@protoc_insertion_point(module_scope)
