# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v1/flavour.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v1/flavour.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.type.v1 import price_pb2 as gpcore_dot_type_dot_v1_dot_price__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!gpcore/api/cloud/v1/flavour.proto\x12\x13gpcore.api.cloud.v1\x1a\x1agpcore/type/v1/price.proto"\xb6\x01\n\x0e\x46lavourMapping\x12\x15\n\rdatacenter_id\x18\x01 \x01(\t\x12\x15\n\tavailable\x18\x02 \x01(\x08\x42\x02\x18\x01\x12\x17\n\x0fpre_order_limit\x18\x03 \x01(\x05\x12-\n\x0eprice_per_hour\x18\x04 \x01(\x0b\x32\x15.gpcore.type.v1.Price\x12.\n\x0fprice_per_month\x18\x05 \x01(\x0b\x32\x15.gpcore.type.v1.Price"\xc3\x02\n\x07\x46lavour\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12>\n\x0c\x61vailability\x18\x04 \x01(\x0e\x32(.gpcore.api.cloud.v1.FlavourAvailability\x12\x0b\n\x03\x63pu\x18\x06 \x01(\t\x12\x0e\n\x06memory\x18\x07 \x01(\t\x12\x0c\n\x04\x64isk\x18\x08 \x01(\t\x12\x0f\n\x07network\x18\t \x01(\t\x12\x0f\n\x07traffic\x18\n \x01(\x03\x12-\n\x0eprice_per_hour\x18\x0b \x01(\x0b\x32\x15.gpcore.type.v1.Price\x12\x32\n\x13windows_monthly_fee\x18\x0c \x01(\x0b\x32\x15.gpcore.type.v1.Price\x12.\n\x0fprice_per_month\x18\r \x01(\x0b\x32\x15.gpcore.type.v1.Price"(\n\x0c\x42\x61sicFlavour\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t*\xe3\x01\n\x13\x46lavourAvailability\x12$\n FLAVOUR_AVAILABILITY_UNSPECIFIED\x10\x00\x12%\n!FLAVOUR_AVAILABILITY_OUT_OF_STOCK\x10\x01\x12!\n\x1d\x46LAVOUR_AVAILABILITY_PREORDER\x10\x02\x12\x1c\n\x18\x46LAVOUR_AVAILABILITY_LOW\x10\x03\x12\x1f\n\x1b\x46LAVOUR_AVAILABILITY_MIDDLE\x10\x04\x12\x1d\n\x19\x46LAVOUR_AVAILABILITY_HIGH\x10\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v1.flavour_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_FLAVOURMAPPING"].fields_by_name["available"]._loaded_options = None
    _globals["_FLAVOURMAPPING"].fields_by_name[
        "available"
    ]._serialized_options = b"\030\001"
    _globals["_FLAVOURAVAILABILITY"]._serialized_start = 640
    _globals["_FLAVOURAVAILABILITY"]._serialized_end = 867
    _globals["_FLAVOURMAPPING"]._serialized_start = 87
    _globals["_FLAVOURMAPPING"]._serialized_end = 269
    _globals["_FLAVOUR"]._serialized_start = 272
    _globals["_FLAVOUR"]._serialized_end = 595
    _globals["_BASICFLAVOUR"]._serialized_start = 597
    _globals["_BASICFLAVOUR"]._serialized_end = 637
# @@protoc_insertion_point(module_scope)
