# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v1/metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v1/metadata.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gpcore_sdk.gpcore.api.cloud.v1 import (
    server_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_server__pb2,
)
from gpcore_sdk.gpcore.type.v1 import (
    ssh_key_pb2 as gpcore_dot_type_dot_v1_dot_ssh__key__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"gpcore/api/cloud/v1/metadata.proto\x12\x13gpcore.api.cloud.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a gpcore/api/cloud/v1/server.proto\x1a\x1cgpcore/type/v1/ssh_key.proto"s\n\x1aMetadataNetworkInterfaceIP\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0f\n\x07netmask\x18\x02 \x01(\t\x12\x0e\n\x06prefix\x18\x03 \x01(\t\x12\x14\n\x07gateway\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_gateway":\n\x1cMetadataNetworkInterfaceVLAN\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06tagged\x18\x02 \x01(\x08"\xaf\x01\n\x18MetadataNetworkInterface\x12\x13\n\x0bmac_address\x18\x01 \x01(\t\x12?\n\x04vlan\x18\x02 \x01(\x0b\x32\x31.gpcore.api.cloud.v1.MetadataNetworkInterfaceVLAN\x12=\n\x04ipv4\x18\x03 \x01(\x0b\x32/.gpcore.api.cloud.v1.MetadataNetworkInterfaceIP")\n\x12MetadataNetworkDNS\x12\x13\n\x0bnameservers\x18\x01 \x03(\t"\x9b\x03\n\x08Metadata\x12\x13\n\x0binstance_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x13\n\x0bvendor_data\x18\x03 \x01(\x0c\x12\x15\n\rvendor_data_2\x18\x04 \x01(\x0c\x12\x11\n\tuser_data\x18\x05 \x01(\x0c\x12\x19\n\x11\x61vailability_zone\x18\x06 \x01(\t\x12\x12\n\nproject_id\x18\x07 \x01(\t\x12\x15\n\x08username\x18\x08 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08password\x18\t \x01(\tH\x01\x88\x01\x01\x12\x0f\n\x07\x66lavour\x18\n \x01(\t\x12(\n\x08ssh_keys\x18\x0b \x03(\x0b\x32\x16.gpcore.type.v1.SSHKey\x12\x41\n\ninterfaces\x18\x0c \x03(\x0b\x32-.gpcore.api.cloud.v1.MetadataNetworkInterface\x12\x34\n\x03\x64ns\x18\r \x01(\x0b\x32\'.gpcore.api.cloud.v1.MetadataNetworkDNSB\x0b\n\t_usernameB\x0b\n\t_password"\x9c\x01\n\x0eMetadataReport\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x36\n\x05level\x18\x03 \x01(\x0e\x32\'.gpcore.api.cloud.v1.ServerLogLevelType\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v1.metadata_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_METADATANETWORKINTERFACEIP"]._serialized_start = 156
    _globals["_METADATANETWORKINTERFACEIP"]._serialized_end = 271
    _globals["_METADATANETWORKINTERFACEVLAN"]._serialized_start = 273
    _globals["_METADATANETWORKINTERFACEVLAN"]._serialized_end = 331
    _globals["_METADATANETWORKINTERFACE"]._serialized_start = 334
    _globals["_METADATANETWORKINTERFACE"]._serialized_end = 509
    _globals["_METADATANETWORKDNS"]._serialized_start = 511
    _globals["_METADATANETWORKDNS"]._serialized_end = 552
    _globals["_METADATA"]._serialized_start = 555
    _globals["_METADATA"]._serialized_end = 966
    _globals["_METADATAREPORT"]._serialized_start = 969
    _globals["_METADATAREPORT"]._serialized_end = 1125
# @@protoc_insertion_point(module_scope)
