# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v1/notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "gpcore/api/cloud/v1/notification.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.cloud.v1 import (
    node_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_node__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    user_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_user__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    project_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_project__pb2,
)
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gpcore_sdk.gpcore.api.cloud.v1 import (
    server_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_server__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n&gpcore/api/cloud/v1/notification.proto\x12\x13gpcore.api.cloud.v1\x1a\x1egpcore/api/cloud/v1/node.proto\x1a\x1egpcore/api/cloud/v1/user.proto\x1a!gpcore/api/cloud/v1/project.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a gpcore/api/cloud/v1/server.proto"\x88\x02\n\x0cNotification\x12)\n\x04user\x18\x01 \x01(\x0b\x32\x19.gpcore.api.cloud.v1.UserH\x00\x12/\n\x07project\x18\x02 \x01(\x0b\x32\x1c.gpcore.api.cloud.v1.ProjectH\x00\x12)\n\x04node\x18\x03 \x01(\x0b\x32\x19.gpcore.api.cloud.v1.NodeH\x00\x12\x34\n\nserver_log\x18\x04 \x01(\x0b\x32\x1e.gpcore.api.cloud.v1.ServerLogH\x00\x12\x30\n\theartbeat\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x42\t\n\x07messageb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v1.notification_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NOTIFICATION"]._serialized_start = 230
    _globals["_NOTIFICATION"]._serialized_end = 494
# @@protoc_insertion_point(module_scope)
