# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v1/region.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v1/region.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n gpcore/api/cloud/v1/region.proto\x12\x13gpcore.api.cloud.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\x8d\x02\n\nDatacenter\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05short\x18\x03 \x01(\t\x12+\n\x06region\x18\x04 \x01(\x0b\x32\x1b.gpcore.api.cloud.v1.Region\x12\x35\n\x06status\x18\x05 \x01(\x0e\x32%.gpcore.api.cloud.v1.DatacenterStatus\x12\x18\n\x10latency_endpoint\x18\x06 \x01(\t\x12\x1b\n\x13management_vlan_ids\x18\x07 \x03(\x05\x12\x15\n\rserver_prefix\x18\x08 \x01(\t\x12\x16\n\tnetbox_id\x18\t \x01(\x03H\x00\x88\x01\x01\x42\x0c\n\n_netbox_id"\xf6\x01\n\x06Region\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x03 \x01(\t\x12\x34\n\x0b\x64\x61tacenters\x18\x04 \x03(\x0b\x32\x1f.gpcore.api.cloud.v1.Datacenter\x12\x16\n\tnetbox_id\x18\x05 \x01(\x03H\x00\x88\x01\x01\x12/\n\ncreated_at\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\nupdated_at\x18\xe9\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0c\n\n_netbox_id*\x9c\x01\n\x10\x44\x61tacenterStatus\x12!\n\x1d\x44\x41TACENTER_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1b\x44\x41TACENTER_STATUS_AVAILABLE\x10\x01\x12!\n\x1d\x44\x41TACENTER_STATUS_COMING_SOON\x10\x02\x12!\n\x1d\x44\x41TACENTER_STATUS_UNAVAILABLE\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v1.region_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DATACENTERSTATUS"]._serialized_start = 612
    _globals["_DATACENTERSTATUS"]._serialized_end = 768
    _globals["_DATACENTER"]._serialized_start = 91
    _globals["_DATACENTER"]._serialized_end = 360
    _globals["_REGION"]._serialized_start = 363
    _globals["_REGION"]._serialized_end = 609
# @@protoc_insertion_point(module_scope)
