# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v1/spla.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v1/spla.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.type.v1 import price_pb2 as gpcore_dot_type_dot_v1_dot_price__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1egpcore/api/cloud/v1/spla.proto\x12\x13gpcore.api.cloud.v1\x1a\x1agpcore/type/v1/price.proto"o\n\tSplaPrice\x12)\n\nbase_price\x18\x01 \x01(\x0b\x32\x15.gpcore.type.v1.Price\x12\x37\n\x18\x61\x64\x64itional_2_cores_price\x18\x02 \x01(\x0b\x32\x15.gpcore.type.v1.Priceb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v1.spla_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SPLAPRICE"]._serialized_start = 83
    _globals["_SPLAPRICE"]._serialized_end = 194
# @@protoc_insertion_point(module_scope)
