# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v1/switch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v1/switch.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n gpcore/api/cloud/v1/switch.proto\x12\x13gpcore.api.cloud.v1"\xb9\x01\n\x06Switch\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.gpcore.api.cloud.v1.SwitchType\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x16\n\tnetbox_id\x18\x08 \x01(\x03H\x00\x88\x01\x01\x42\x0c\n\n_netbox_idJ\x04\x08\x04\x10\x06J\x04\x08\x07\x10\x08R\x08usernameR\x08passwordR\x0cuplink_ports*\x92\x01\n\nSwitchType\x12\x1b\n\x17SWITCH_TYPE_UNSPECIFIED\x10\x00\x12\x17\n\x13SWITCH_TYPE_JUNIPER\x10\x01\x12\x1e\n\x1aSWITCH_TYPE_JUNIPER_LEGACY\x10\x02\x12\x12\n\x0eSWITCH_TYPE_FS\x10\x03\x12\x1a\n\x16SWITCH_TYPE_ARISTA_EOS\x10\x04\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v1.switch_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SWITCHTYPE"]._serialized_start = 246
    _globals["_SWITCHTYPE"]._serialized_end = 392
    _globals["_SWITCH"]._serialized_start = 58
    _globals["_SWITCH"]._serialized_end = 243
# @@protoc_insertion_point(module_scope)
