# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v1/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v1/user.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1egpcore/api/cloud/v1/user.proto\x12\x13gpcore.api.cloud.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\x80\x02\n\tBasicUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x16\n\tfull_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x12\n\navatar_url\x18\x05 \x01(\t\x12+\n\x04type\x18\x06 \x01(\x0e\x32\x1d.gpcore.api.cloud.v1.UserType\x12\x10\n\x08timezone\x18\x07 \x01(\t\x12*\n\x04tags\x18\x08 \x03(\x0e\x32\x1c.gpcore.api.cloud.v1.UserTag\x12\x12\n\nnode_limit\x18\t \x01(\x05\x42\x0c\n\n_full_nameB\x08\n\x06_email"\x8b\x04\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\t\x12\x16\n\tfull_name\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x11\n\tconfirmed\x18\x06 \x01(\x08\x12\x0e\n\x06locked\x18\x07 \x01(\x08\x12\x12\n\navatar_url\x18\x08 \x01(\t\x12\x12\n\nnode_limit\x18\t \x01(\x05\x12\x13\n\x0bkeycloak_id\x18\x0b \x01(\t\x12+\n\x04type\x18\x0c \x01(\x0e\x32\x1d.gpcore.api.cloud.v1.UserType\x12\x10\n\x08timezone\x18\r \x01(\t\x12*\n\x04tags\x18\x0e \x03(\x0e\x32\x1c.gpcore.api.cloud.v1.UserTag\x12\x19\n\x11\x64\x65\x66\x61ult_plan_code\x18\x0f \x01(\t\x12\x32\n\rlast_login_at\x18\xe7\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\ncreated_at\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\nupdated_at\x18\xe9\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x0c\n\n_full_nameB\x08\n\x06_emailJ\x04\x08\n\x10\x0bR\x0fpayment_methods*X\n\x08UserType\x12\x19\n\x15USER_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eUSER_TYPE_USER\x10\x01\x12\x1d\n\x19USER_TYPE_SERVICE_ACCOUNT\x10\x02*\x81\x01\n\x07UserTag\x12\x18\n\x14USER_TAG_UNSPECIFIED\x10\x00\x12\x17\n\x13USER_TAG_NO_COMPANY\x10\x01\x12\x1b\n\x17USER_TAG_NO_CREDIT_CARD\x10\x02\x12&\n"USER_TAG_ACCESS_TO_CLOUD_PROVIDERS\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v1.user_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USERTYPE"]._serialized_start = 873
    _globals["_USERTYPE"]._serialized_end = 961
    _globals["_USERTAG"]._serialized_start = 964
    _globals["_USERTAG"]._serialized_end = 1093
    _globals["_BASICUSER"]._serialized_start = 89
    _globals["_BASICUSER"]._serialized_end = 345
    _globals["_USER"]._serialized_start = 348
    _globals["_USER"]._serialized_end = 871
# @@protoc_insertion_point(module_scope)
