# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/payment/v1/responses.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "gpcore/api/payment/v1/responses.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.type.v1 import (
    credit_card_pb2 as gpcore_dot_type_dot_v1_dot_credit__card__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    billing_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_billing__pb2,
)
from gpcore_sdk.gpcore.type.v1 import (
    pagination_pb2 as gpcore_dot_type_dot_v1_dot_pagination__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%gpcore/api/payment/v1/responses.proto\x12\x15gpcore.api.payment.v1\x1a gpcore/type/v1/credit_card.proto\x1a!gpcore/api/cloud/v1/billing.proto\x1a\x1fgpcore/type/v1/pagination.proto"\xa6\x01\n\x17ListCreditCardsResponse\x12\x30\n\x0c\x63redit_cards\x18\x01 \x03(\x0b\x32\x1a.gpcore.type.v1.CreditCard\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05total\x18\x03 \x01(\x03\x42\r\n\x0b_pagination"3\n\x15\x41\x64\x64\x43reditCardResponse\x12\x1a\n\x12stripe_setup_ident\x18\x01 \x01(\t"\x1a\n\x18RemoveCreditCardResponse"\\\n\x1c\x43reateBillingProfileResponse\x12<\n\x0f\x62illing_profile\x18\x01 \x01(\x0b\x32#.gpcore.api.cloud.v1.BillingProfile"R\n\x1f\x43hangeDefaultCreditCardResponse\x12/\n\x0b\x63redit_card\x18\x01 \x01(\x0b\x32\x1a.gpcore.type.v1.CreditCard"\\\n\x1cUpdateBillingProfileResponse\x12<\n\x0f\x62illing_profile\x18\x01 \x01(\x0b\x32#.gpcore.api.cloud.v1.BillingProfile"\xb7\x01\n\x1bListBillingProfilesResponse\x12=\n\x10\x62illing_profiles\x18\x01 \x03(\x0b\x32#.gpcore.api.cloud.v1.BillingProfile\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05total\x18\x03 \x01(\x03\x42\r\n\x0b_pagination"\x1e\n\x1c\x44\x65leteBillingProfileResponse"\x86\x01\n\x15ListPlanCodesResponse\x12\x12\n\nplan_codes\x18\x01 \x03(\t\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05total\x18\x03 \x01(\x03\x42\r\n\x0b_pagination"/\n\x1aGetDefaultPlanCodeResponse\x12\x11\n\tplan_code\x18\x01 \x01(\t"2\n\x1d\x43hangeDefaultPlanCodeResponse\x12\x11\n\tplan_code\x18\x01 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.payment.v1.responses_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LISTCREDITCARDSRESPONSE"]._serialized_start = 167
    _globals["_LISTCREDITCARDSRESPONSE"]._serialized_end = 333
    _globals["_ADDCREDITCARDRESPONSE"]._serialized_start = 335
    _globals["_ADDCREDITCARDRESPONSE"]._serialized_end = 386
    _globals["_REMOVECREDITCARDRESPONSE"]._serialized_start = 388
    _globals["_REMOVECREDITCARDRESPONSE"]._serialized_end = 414
    _globals["_CREATEBILLINGPROFILERESPONSE"]._serialized_start = 416
    _globals["_CREATEBILLINGPROFILERESPONSE"]._serialized_end = 508
    _globals["_CHANGEDEFAULTCREDITCARDRESPONSE"]._serialized_start = 510
    _globals["_CHANGEDEFAULTCREDITCARDRESPONSE"]._serialized_end = 592
    _globals["_UPDATEBILLINGPROFILERESPONSE"]._serialized_start = 594
    _globals["_UPDATEBILLINGPROFILERESPONSE"]._serialized_end = 686
    _globals["_LISTBILLINGPROFILESRESPONSE"]._serialized_start = 689
    _globals["_LISTBILLINGPROFILESRESPONSE"]._serialized_end = 872
    _globals["_DELETEBILLINGPROFILERESPONSE"]._serialized_start = 874
    _globals["_DELETEBILLINGPROFILERESPONSE"]._serialized_end = 904
    _globals["_LISTPLANCODESRESPONSE"]._serialized_start = 907
    _globals["_LISTPLANCODESRESPONSE"]._serialized_end = 1041
    _globals["_GETDEFAULTPLANCODERESPONSE"]._serialized_start = 1043
    _globals["_GETDEFAULTPLANCODERESPONSE"]._serialized_end = 1090
    _globals["_CHANGEDEFAULTPLANCODERESPONSE"]._serialized_start = 1092
    _globals["_CHANGEDEFAULTPLANCODERESPONSE"]._serialized_end = 1142
# @@protoc_insertion_point(module_scope)
