# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/payment/v1/rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/payment/v1/rpc.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.v1 import options_pb2 as gpcore_dot_v1_dot_options__pb2
from gpcore_sdk.gpcore.api.payment.v1 import (
    requests_pb2 as gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.payment.v1 import (
    responses_pb2 as gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgpcore/api/payment/v1/rpc.proto\x12\x15gpcore.api.payment.v1\x1a\x17gpcore/v1/options.proto\x1a$gpcore/api/payment/v1/requests.proto\x1a%gpcore/api/payment/v1/responses.proto2\xaa\x0b\n\x0ePaymentService\x12r\n\x0fListCreditCards\x12-.gpcore.api.payment.v1.ListCreditCardsRequest\x1a..gpcore.api.payment.v1.ListCreditCardsResponse"\x00\x12l\n\rAddCreditCard\x12+.gpcore.api.payment.v1.AddCreditCardRequest\x1a,.gpcore.api.payment.v1.AddCreditCardResponse"\x00\x12\x8a\x01\n\x17\x43hangeDefaultCreditCard\x12\x35.gpcore.api.payment.v1.ChangeDefaultCreditCardRequest\x1a\x36.gpcore.api.payment.v1.ChangeDefaultCreditCardResponse"\x00\x12u\n\x10RemoveCreditCard\x12..gpcore.api.payment.v1.RemoveCreditCardRequest\x1a/.gpcore.api.payment.v1.RemoveCreditCardResponse"\x00\x12~\n\x13ListBillingProfiles\x12\x31.gpcore.api.payment.v1.ListBillingProfilesRequest\x1a\x32.gpcore.api.payment.v1.ListBillingProfilesResponse"\x00\x12\x81\x01\n\x14\x43reateBillingProfile\x12\x32.gpcore.api.payment.v1.CreateBillingProfileRequest\x1a\x33.gpcore.api.payment.v1.CreateBillingProfileResponse"\x00\x12\x81\x01\n\x14UpdateBillingProfile\x12\x32.gpcore.api.payment.v1.UpdateBillingProfileRequest\x1a\x33.gpcore.api.payment.v1.UpdateBillingProfileResponse"\x00\x12\x81\x01\n\x14\x44\x65leteBillingProfile\x12\x32.gpcore.api.payment.v1.DeleteBillingProfileRequest\x1a\x33.gpcore.api.payment.v1.DeleteBillingProfileResponse"\x00\x12\x8c\x01\n\x12GetDefaultPlanCode\x12\x30.gpcore.api.payment.v1.GetDefaultPlanCodeRequest\x1a\x31.gpcore.api.payment.v1.GetDefaultPlanCodeResponse"\x11\xe2\x44\x0e\x12\x0cview-payment\x12\x97\x01\n\x15\x43hangeDefaultPlanCode\x12\x33.gpcore.api.payment.v1.ChangeDefaultPlanCodeRequest\x1a\x34.gpcore.api.payment.v1.ChangeDefaultPlanCodeResponse"\x13\xe2\x44\x10\x12\x0emanage-payment\x12}\n\rListPlanCodes\x12+.gpcore.api.payment.v1.ListPlanCodesRequest\x1a,.gpcore.api.payment.v1.ListPlanCodesResponse"\x11\xe2\x44\x0e\x12\x0cview-paymentb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.payment.v1.rpc_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PAYMENTSERVICE"].methods_by_name[
        "GetDefaultPlanCode"
    ]._loaded_options = None
    _globals["_PAYMENTSERVICE"].methods_by_name[
        "GetDefaultPlanCode"
    ]._serialized_options = b"\342D\016\022\014view-payment"
    _globals["_PAYMENTSERVICE"].methods_by_name[
        "ChangeDefaultPlanCode"
    ]._loaded_options = None
    _globals["_PAYMENTSERVICE"].methods_by_name[
        "ChangeDefaultPlanCode"
    ]._serialized_options = b"\342D\020\022\016manage-payment"
    _globals["_PAYMENTSERVICE"].methods_by_name["ListPlanCodes"]._loaded_options = None
    _globals["_PAYMENTSERVICE"].methods_by_name[
        "ListPlanCodes"
    ]._serialized_options = b"\342D\016\022\014view-payment"
    _globals["_PAYMENTSERVICE"]._serialized_start = 161
    _globals["_PAYMENTSERVICE"]._serialized_end = 1611
# @@protoc_insertion_point(module_scope)
