# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from gpcore_sdk.gpcore.api.payment.v1 import (
    requests_pb2 as gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.payment.v1 import (
    responses_pb2 as gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2,
)

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in gpcore/api/payment/v1/rpc_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCreditCards = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/ListCreditCards",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListCreditCardsRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListCreditCardsResponse.FromString,
            _registered_method=True,
        )
        self.AddCreditCard = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/AddCreditCard",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.AddCreditCardRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.AddCreditCardResponse.FromString,
            _registered_method=True,
        )
        self.ChangeDefaultCreditCard = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/ChangeDefaultCreditCard",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ChangeDefaultCreditCardRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ChangeDefaultCreditCardResponse.FromString,
            _registered_method=True,
        )
        self.RemoveCreditCard = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/RemoveCreditCard",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.RemoveCreditCardRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.RemoveCreditCardResponse.FromString,
            _registered_method=True,
        )
        self.ListBillingProfiles = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/ListBillingProfiles",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListBillingProfilesRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListBillingProfilesResponse.FromString,
            _registered_method=True,
        )
        self.CreateBillingProfile = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/CreateBillingProfile",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.CreateBillingProfileRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.CreateBillingProfileResponse.FromString,
            _registered_method=True,
        )
        self.UpdateBillingProfile = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/UpdateBillingProfile",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.UpdateBillingProfileRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.UpdateBillingProfileResponse.FromString,
            _registered_method=True,
        )
        self.DeleteBillingProfile = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/DeleteBillingProfile",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.DeleteBillingProfileRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.DeleteBillingProfileResponse.FromString,
            _registered_method=True,
        )
        self.GetDefaultPlanCode = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/GetDefaultPlanCode",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.GetDefaultPlanCodeRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.GetDefaultPlanCodeResponse.FromString,
            _registered_method=True,
        )
        self.ChangeDefaultPlanCode = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/ChangeDefaultPlanCode",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ChangeDefaultPlanCodeRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ChangeDefaultPlanCodeResponse.FromString,
            _registered_method=True,
        )
        self.ListPlanCodes = channel.unary_unary(
            "/gpcore.api.payment.v1.PaymentService/ListPlanCodes",
            request_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListPlanCodesRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListPlanCodesResponse.FromString,
            _registered_method=True,
        )


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCreditCards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ChangeDefaultCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListBillingProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateBillingProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateBillingProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteBillingProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDefaultPlanCode(self, request, context):
        """GetDefaultPlanCode requests the default plan code (lago identifier) for
        a given billing profile. The response is the lago default plan code, represented
        as a string. This identifier is used to set a payment plan for new projects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ChangeDefaultPlanCode(self, request, context):
        """ChangeDefaultPlanCode changes the current default plan code on a given
        billing profile. The given default plan will be checked against Lago if it
        exists. This change only affects projects created in the future. Already
        created projects are not affected. To change the plan for existing projects,
        you need to do that directly in Lago.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPlanCodes(self, request, context):
        """ListPlanCodes list all available plan codes in lago, including the default
        plan codes "free" and "gpcore".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListCreditCards": grpc.unary_unary_rpc_method_handler(
            servicer.ListCreditCards,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListCreditCardsRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListCreditCardsResponse.SerializeToString,
        ),
        "AddCreditCard": grpc.unary_unary_rpc_method_handler(
            servicer.AddCreditCard,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.AddCreditCardRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.AddCreditCardResponse.SerializeToString,
        ),
        "ChangeDefaultCreditCard": grpc.unary_unary_rpc_method_handler(
            servicer.ChangeDefaultCreditCard,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ChangeDefaultCreditCardRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ChangeDefaultCreditCardResponse.SerializeToString,
        ),
        "RemoveCreditCard": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveCreditCard,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.RemoveCreditCardRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.RemoveCreditCardResponse.SerializeToString,
        ),
        "ListBillingProfiles": grpc.unary_unary_rpc_method_handler(
            servicer.ListBillingProfiles,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListBillingProfilesRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListBillingProfilesResponse.SerializeToString,
        ),
        "CreateBillingProfile": grpc.unary_unary_rpc_method_handler(
            servicer.CreateBillingProfile,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.CreateBillingProfileRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.CreateBillingProfileResponse.SerializeToString,
        ),
        "UpdateBillingProfile": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateBillingProfile,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.UpdateBillingProfileRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.UpdateBillingProfileResponse.SerializeToString,
        ),
        "DeleteBillingProfile": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteBillingProfile,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.DeleteBillingProfileRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.DeleteBillingProfileResponse.SerializeToString,
        ),
        "GetDefaultPlanCode": grpc.unary_unary_rpc_method_handler(
            servicer.GetDefaultPlanCode,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.GetDefaultPlanCodeRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.GetDefaultPlanCodeResponse.SerializeToString,
        ),
        "ChangeDefaultPlanCode": grpc.unary_unary_rpc_method_handler(
            servicer.ChangeDefaultPlanCode,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ChangeDefaultPlanCodeRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ChangeDefaultPlanCodeResponse.SerializeToString,
        ),
        "ListPlanCodes": grpc.unary_unary_rpc_method_handler(
            servicer.ListPlanCodes,
            request_deserializer=gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListPlanCodesRequest.FromString,
            response_serializer=gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListPlanCodesResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "gpcore.api.payment.v1.PaymentService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "gpcore.api.payment.v1.PaymentService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCreditCards(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/ListCreditCards",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListCreditCardsRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListCreditCardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddCreditCard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/AddCreditCard",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.AddCreditCardRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.AddCreditCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChangeDefaultCreditCard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/ChangeDefaultCreditCard",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ChangeDefaultCreditCardRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ChangeDefaultCreditCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemoveCreditCard(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/RemoveCreditCard",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.RemoveCreditCardRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.RemoveCreditCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListBillingProfiles(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/ListBillingProfiles",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListBillingProfilesRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListBillingProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateBillingProfile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/CreateBillingProfile",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.CreateBillingProfileRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.CreateBillingProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateBillingProfile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/UpdateBillingProfile",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.UpdateBillingProfileRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.UpdateBillingProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteBillingProfile(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/DeleteBillingProfile",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.DeleteBillingProfileRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.DeleteBillingProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDefaultPlanCode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/GetDefaultPlanCode",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.GetDefaultPlanCodeRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.GetDefaultPlanCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ChangeDefaultPlanCode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/ChangeDefaultPlanCode",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ChangeDefaultPlanCodeRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ChangeDefaultPlanCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPlanCodes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.payment.v1.PaymentService/ListPlanCodes",
            gpcore_dot_api_dot_payment_dot_v1_dot_requests__pb2.ListPlanCodesRequest.SerializeToString,
            gpcore_dot_api_dot_payment_dot_v1_dot_responses__pb2.ListPlanCodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
