# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/metadata/v1/requests.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "gpcore/api/metadata/v1/requests.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.cloud.v1 import (
    metadata_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_metadata__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%gpcore/api/metadata/v1/requests.proto\x12\x16gpcore.api.metadata.v1\x1a"gpcore/api/cloud/v1/metadata.proto"(\n\x12GetMetadataRequest\x12\x12\n\nip_address\x18\x01 \x01(\t"D\n\rReportRequest\x12\x33\n\x06report\x18\x01 \x01(\x0b\x32#.gpcore.api.cloud.v1.MetadataReportb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.metadata.v1.requests_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETMETADATAREQUEST"]._serialized_start = 101
    _globals["_GETMETADATAREQUEST"]._serialized_end = 141
    _globals["_REPORTREQUEST"]._serialized_start = 143
    _globals["_REPORTREQUEST"]._serialized_end = 211
# @@protoc_insertion_point(module_scope)
