# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/metadata/v1/rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/metadata/v1/rpc.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.v1 import options_pb2 as gpcore_dot_v1_dot_options__pb2
from gpcore_sdk.gpcore.api.metadata.v1 import (
    requests_pb2 as gpcore_dot_api_dot_metadata_dot_v1_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.metadata.v1 import (
    responses_pb2 as gpcore_dot_api_dot_metadata_dot_v1_dot_responses__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n gpcore/api/metadata/v1/rpc.proto\x12\x16gpcore.api.metadata.v1\x1a\x17gpcore/v1/options.proto\x1a%gpcore/api/metadata/v1/requests.proto\x1a&gpcore/api/metadata/v1/responses.proto2\xe0\x01\n\x0fMetadataService\x12m\n\x0bGetMetadata\x12*.gpcore.api.metadata.v1.GetMetadataRequest\x1a+.gpcore.api.metadata.v1.GetMetadataResponse"\x05\xe2\x44\x02\x08\x03\x12^\n\x06Report\x12%.gpcore.api.metadata.v1.ReportRequest\x1a&.gpcore.api.metadata.v1.ReportResponse"\x05\xe2\x44\x02\x08\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.metadata.v1.rpc_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_METADATASERVICE"].methods_by_name["GetMetadata"]._loaded_options = None
    _globals["_METADATASERVICE"].methods_by_name[
        "GetMetadata"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_METADATASERVICE"].methods_by_name["Report"]._loaded_options = None
    _globals["_METADATASERVICE"].methods_by_name[
        "Report"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_METADATASERVICE"]._serialized_start = 165
    _globals["_METADATASERVICE"]._serialized_end = 389
# @@protoc_insertion_point(module_scope)
