# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/auth/v1/client.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/auth/v1/client.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gpcore_sdk.gpcore.api.cloud.v1 import (
    user_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_user__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgpcore/api/auth/v1/client.proto\x12\x12gpcore.api.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egpcore/api/cloud/v1/user.proto"\xf2\x01\n\x06\x43lient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x37\n\x0fservice_account\x18\x04 \x01(\x0b\x32\x1e.gpcore.api.cloud.v1.BasicUser\x12\x13\n\x06secret\x18\x05 \x01(\tH\x00\x88\x01\x01\x12/\n\ncreated_at\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\nupdated_at\x18\xe9\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\t\n\x07_secretb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.auth.v1.client_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CLIENT"]._serialized_start = 121
    _globals["_CLIENT"]._serialized_end = 363
# @@protoc_insertion_point(module_scope)
