# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/auth/v1/requests.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/auth/v1/requests.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from gpcore_sdk.gpcore.type.v1 import (
    pagination_pb2 as gpcore_dot_type_dot_v1_dot_pagination__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!gpcore/api/auth/v1/requests.proto\x12\x12gpcore.api.auth.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1fgpcore/type/v1/pagination.proto"\x9f\x01\n\x0fRegisterRequest\x12\x16\n\x05\x65mail\x18\x01 \x01(\tB\x07\xbaH\x04r\x02`\x01\x12\x19\n\x08password\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x08\x12 \n\x0frecaptcha_token\x18\x03 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x12\x1b\n\nfirst_name\x18\x04 \x01(\tB\x07\xbaH\x04r\x02\x10\x02\x12\x1a\n\tlast_name\x18\x05 \x01(\tB\x07\xbaH\x04r\x02\x10\x02"\x10\n\x0eGetUserRequest"\x1b\n\x19ResendConfirmEMailRequest"_\n\x12ListClientsRequest\x12:\n\npagination\x18\x01 \x01(\x0b\x32!.gpcore.type.v1.PaginationRequestH\x00\x88\x01\x01\x42\r\n\x0b_pagination"8\n\x13\x43reateClientRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t"\x1e\n\x10GetClientRequest\x12\n\n\x02id\x18\x01 \x01(\t"D\n\x13UpdateClientRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t"!\n\x13\x44\x65leteClientRequest\x12\n\n\x02id\x18\x01 \x01(\t"&\n\x18ResetClientSecretRequest\x12\n\n\x02id\x18\x01 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.auth.v1.requests_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REGISTERREQUEST"].fields_by_name["email"]._loaded_options = None
    _globals["_REGISTERREQUEST"].fields_by_name[
        "email"
    ]._serialized_options = b"\272H\004r\002`\001"
    _globals["_REGISTERREQUEST"].fields_by_name["password"]._loaded_options = None
    _globals["_REGISTERREQUEST"].fields_by_name[
        "password"
    ]._serialized_options = b"\272H\004r\002\020\010"
    _globals["_REGISTERREQUEST"].fields_by_name[
        "recaptcha_token"
    ]._loaded_options = None
    _globals["_REGISTERREQUEST"].fields_by_name[
        "recaptcha_token"
    ]._serialized_options = b"\272H\004r\002\020\001"
    _globals["_REGISTERREQUEST"].fields_by_name["first_name"]._loaded_options = None
    _globals["_REGISTERREQUEST"].fields_by_name[
        "first_name"
    ]._serialized_options = b"\272H\004r\002\020\002"
    _globals["_REGISTERREQUEST"].fields_by_name["last_name"]._loaded_options = None
    _globals["_REGISTERREQUEST"].fields_by_name[
        "last_name"
    ]._serialized_options = b"\272H\004r\002\020\002"
    _globals["_REGISTERREQUEST"]._serialized_start = 120
    _globals["_REGISTERREQUEST"]._serialized_end = 279
    _globals["_GETUSERREQUEST"]._serialized_start = 281
    _globals["_GETUSERREQUEST"]._serialized_end = 297
    _globals["_RESENDCONFIRMEMAILREQUEST"]._serialized_start = 299
    _globals["_RESENDCONFIRMEMAILREQUEST"]._serialized_end = 326
    _globals["_LISTCLIENTSREQUEST"]._serialized_start = 328
    _globals["_LISTCLIENTSREQUEST"]._serialized_end = 423
    _globals["_CREATECLIENTREQUEST"]._serialized_start = 425
    _globals["_CREATECLIENTREQUEST"]._serialized_end = 481
    _globals["_GETCLIENTREQUEST"]._serialized_start = 483
    _globals["_GETCLIENTREQUEST"]._serialized_end = 513
    _globals["_UPDATECLIENTREQUEST"]._serialized_start = 515
    _globals["_UPDATECLIENTREQUEST"]._serialized_end = 583
    _globals["_DELETECLIENTREQUEST"]._serialized_start = 585
    _globals["_DELETECLIENTREQUEST"]._serialized_end = 618
    _globals["_RESETCLIENTSECRETREQUEST"]._serialized_start = 620
    _globals["_RESETCLIENTSECRETREQUEST"]._serialized_end = 658
# @@protoc_insertion_point(module_scope)
