# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/auth/v1/responses.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/auth/v1/responses.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.auth.v1 import (
    client_pb2 as gpcore_dot_api_dot_auth_dot_v1_dot_client__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    user_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_user__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    token_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_token__pb2,
)
from gpcore_sdk.gpcore.type.v1 import (
    pagination_pb2 as gpcore_dot_type_dot_v1_dot_pagination__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"gpcore/api/auth/v1/responses.proto\x12\x12gpcore.api.auth.v1\x1a\x1fgpcore/api/auth/v1/client.proto\x1a\x1egpcore/api/cloud/v1/user.proto\x1a\x1fgpcore/api/cloud/v1/token.proto\x1a\x1fgpcore/type/v1/pagination.proto"q\n\x10RegisterResponse\x12\'\n\x04user\x18\x01 \x01(\x0b\x32\x19.gpcore.api.cloud.v1.User\x12\x34\n\x06tokens\x18\x02 \x01(\x0b\x32$.gpcore.api.cloud.v1.AccessTokenPair":\n\x0fGetUserResponse\x12\'\n\x04user\x18\x01 \x01(\x0b\x32\x19.gpcore.api.cloud.v1.User"\x1c\n\x1aResendConfirmEMailResponse"\x9d\x01\n\x13ListClientsResponse\x12+\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x1a.gpcore.api.auth.v1.Client\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05total\x18\x03 \x01(\x03\x42\r\n\x0b_pagination"B\n\x14\x43reateClientResponse\x12*\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x1a.gpcore.api.auth.v1.Client"?\n\x11GetClientResponse\x12*\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x1a.gpcore.api.auth.v1.Client"B\n\x14UpdateClientResponse\x12*\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x1a.gpcore.api.auth.v1.Client"\x16\n\x14\x44\x65leteClientResponse"+\n\x19ResetClientSecretResponse\x12\x0e\n\x06secret\x18\x01 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.auth.v1.responses_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_REGISTERRESPONSE"]._serialized_start = 189
    _globals["_REGISTERRESPONSE"]._serialized_end = 302
    _globals["_GETUSERRESPONSE"]._serialized_start = 304
    _globals["_GETUSERRESPONSE"]._serialized_end = 362
    _globals["_RESENDCONFIRMEMAILRESPONSE"]._serialized_start = 364
    _globals["_RESENDCONFIRMEMAILRESPONSE"]._serialized_end = 392
    _globals["_LISTCLIENTSRESPONSE"]._serialized_start = 395
    _globals["_LISTCLIENTSRESPONSE"]._serialized_end = 552
    _globals["_CREATECLIENTRESPONSE"]._serialized_start = 554
    _globals["_CREATECLIENTRESPONSE"]._serialized_end = 620
    _globals["_GETCLIENTRESPONSE"]._serialized_start = 622
    _globals["_GETCLIENTRESPONSE"]._serialized_end = 685
    _globals["_UPDATECLIENTRESPONSE"]._serialized_start = 687
    _globals["_UPDATECLIENTRESPONSE"]._serialized_end = 753
    _globals["_DELETECLIENTRESPONSE"]._serialized_start = 755
    _globals["_DELETECLIENTRESPONSE"]._serialized_end = 777
    _globals["_RESETCLIENTSECRETRESPONSE"]._serialized_start = 779
    _globals["_RESETCLIENTSECRETRESPONSE"]._serialized_end = 822
# @@protoc_insertion_point(module_scope)
