# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/auth/v1/rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/auth/v1/rpc.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.v1 import options_pb2 as gpcore_dot_v1_dot_options__pb2
from gpcore_sdk.gpcore.api.auth.v1 import (
    requests_pb2 as gpcore_dot_api_dot_auth_dot_v1_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.auth.v1 import (
    responses_pb2 as gpcore_dot_api_dot_auth_dot_v1_dot_responses__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cgpcore/api/auth/v1/rpc.proto\x12\x12gpcore.api.auth.v1\x1a\x17gpcore/v1/options.proto\x1a!gpcore/api/auth/v1/requests.proto\x1a"gpcore/api/auth/v1/responses.proto2\x99\x07\n\x0b\x41uthService\x12\\\n\x08Register\x12#.gpcore.api.auth.v1.RegisterRequest\x1a$.gpcore.api.auth.v1.RegisterResponse"\x05\xe2\x44\x02\x08\x01\x12T\n\x07GetUser\x12".gpcore.api.auth.v1.GetUserRequest\x1a#.gpcore.api.auth.v1.GetUserResponse"\x00\x12u\n\x12ResendConfirmEMail\x12-.gpcore.api.auth.v1.ResendConfirmEMailRequest\x1a..gpcore.api.auth.v1.ResendConfirmEMailResponse"\x00\x12`\n\x0bListClients\x12&.gpcore.api.auth.v1.ListClientsRequest\x1a\'.gpcore.api.auth.v1.ListClientsResponse"\x00\x12\x63\n\x0c\x43reateClient\x12\'.gpcore.api.auth.v1.CreateClientRequest\x1a(.gpcore.api.auth.v1.CreateClientResponse"\x00\x12Z\n\tGetClient\x12$.gpcore.api.auth.v1.GetClientRequest\x1a%.gpcore.api.auth.v1.GetClientResponse"\x00\x12\x63\n\x0cUpdateClient\x12\'.gpcore.api.auth.v1.UpdateClientRequest\x1a(.gpcore.api.auth.v1.UpdateClientResponse"\x00\x12\x63\n\x0c\x44\x65leteClient\x12\'.gpcore.api.auth.v1.DeleteClientRequest\x1a(.gpcore.api.auth.v1.DeleteClientResponse"\x00\x12r\n\x11ResetClientSecret\x12,.gpcore.api.auth.v1.ResetClientSecretRequest\x1a-.gpcore.api.auth.v1.ResetClientSecretResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.auth.v1.rpc_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUTHSERVICE"].methods_by_name["Register"]._loaded_options = None
    _globals["_AUTHSERVICE"].methods_by_name[
        "Register"
    ]._serialized_options = b"\342D\002\010\001"
    _globals["_AUTHSERVICE"]._serialized_start = 149
    _globals["_AUTHSERVICE"]._serialized_end = 1070
# @@protoc_insertion_point(module_scope)
