# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/v1/options.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/v1/options.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from gpcore_sdk.google.rpc import (
    error_details_pb2 as google_dot_rpc_dot_error__details__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17gpcore/v1/options.proto\x12\tgpcore.v1\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/rpc/error_details.proto"u\n\x0eGPCORESettings\x12\x38\n\x12\x61uthorization_type\x18\x01 \x01(\x0e\x32\x1c.gpcore.v1.AuthorizationType\x12\x16\n\x0erequired_roles\x18\x02 \x03(\t\x12\x11\n\taudiences\x18\x03 \x03(\t"2\n\x05\x44ummy\x12)\n\ndebug_info\x18\x01 \x01(\x0b\x32\x15.google.rpc.DebugInfo*\x92\x01\n\x11\x41uthorizationType\x12"\n\x1e\x41UTHORIZATION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x41UTHORIZATION_TYPE_PUBLIC\x10\x01\x12\x1b\n\x17\x41UTHORIZATION_TYPE_USER\x10\x02\x12\x1d\n\x19\x41UTHORIZATION_TYPE_CLIENT\x10\x03:G\n\x03\x61pi\x12\x1e.google.protobuf.MethodOptions\x18\xcc\x08 \x01(\x0b\x32\x19.gpcore.v1.GPCORESettingsb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "gpcore.v1.options_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUTHORIZATIONTYPE"]._serialized_start = 276
    _globals["_AUTHORIZATIONTYPE"]._serialized_end = 422
    _globals["_GPCORESETTINGS"]._serialized_start = 104
    _globals["_GPCORESETTINGS"]._serialized_end = 221
    _globals["_DUMMY"]._serialized_start = 223
    _globals["_DUMMY"]._serialized_end = 273
# @@protoc_insertion_point(module_scope)
