# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/gateway/v1/responses.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "gpcore/api/gateway/v1/responses.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.cloud.v1 import (
    image_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_image__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%gpcore/api/gateway/v1/responses.proto\x12\x15gpcore.api.gateway.v1\x1a\x1fgpcore/api/cloud/v1/image.proto"W\n\x1bImageUploadValidateResponse\x12\x38\n\rimage_version\x18\x01 \x01(\x0b\x32!.gpcore.api.cloud.v1.ImageVersion"\x1c\n\x1aImageUploadConfirmResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.gateway.v1.responses_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_IMAGEUPLOADVALIDATERESPONSE"]._serialized_start = 97
    _globals["_IMAGEUPLOADVALIDATERESPONSE"]._serialized_end = 184
    _globals["_IMAGEUPLOADCONFIRMRESPONSE"]._serialized_start = 186
    _globals["_IMAGEUPLOADCONFIRMRESPONSE"]._serialized_end = 214
# @@protoc_insertion_point(module_scope)
