# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/gateway/v1/rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/gateway/v1/rpc.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.v1 import options_pb2 as gpcore_dot_v1_dot_options__pb2
from gpcore_sdk.gpcore.api.gateway.v1 import (
    requests_pb2 as gpcore_dot_api_dot_gateway_dot_v1_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.gateway.v1 import (
    responses_pb2 as gpcore_dot_api_dot_gateway_dot_v1_dot_responses__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgpcore/api/gateway/v1/rpc.proto\x12\x15gpcore.api.gateway.v1\x1a\x17gpcore/v1/options.proto\x1a$gpcore/api/gateway/v1/requests.proto\x1a%gpcore/api/gateway/v1/responses.proto2\x99\x02\n\x0eGatewayService\x12\x83\x01\n\x13ImageUploadValidate\x12\x31.gpcore.api.gateway.v1.ImageUploadValidateRequest\x1a\x32.gpcore.api.gateway.v1.ImageUploadValidateResponse"\x05\xe2\x44\x02\x08\x03\x12\x80\x01\n\x12ImageUploadConfirm\x12\x30.gpcore.api.gateway.v1.ImageUploadConfirmRequest\x1a\x31.gpcore.api.gateway.v1.ImageUploadConfirmResponse"\x05\xe2\x44\x02\x08\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.gateway.v1.rpc_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GATEWAYSERVICE"].methods_by_name[
        "ImageUploadValidate"
    ]._loaded_options = None
    _globals["_GATEWAYSERVICE"].methods_by_name[
        "ImageUploadValidate"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_GATEWAYSERVICE"].methods_by_name[
        "ImageUploadConfirm"
    ]._loaded_options = None
    _globals["_GATEWAYSERVICE"].methods_by_name[
        "ImageUploadConfirm"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_GATEWAYSERVICE"]._serialized_start = 161
    _globals["_GATEWAYSERVICE"]._serialized_end = 442
# @@protoc_insertion_point(module_scope)
