# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from gpcore_sdk.gpcore.api.gateway.v1 import (
    requests_pb2 as gpcore_dot_api_dot_gateway_dot_v1_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.gateway.v1 import (
    responses_pb2 as gpcore_dot_api_dot_gateway_dot_v1_dot_responses__pb2,
)

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in gpcore/api/gateway/v1/rpc_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageUploadValidate = channel.unary_unary(
            "/gpcore.api.gateway.v1.GatewayService/ImageUploadValidate",
            request_serializer=gpcore_dot_api_dot_gateway_dot_v1_dot_requests__pb2.ImageUploadValidateRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_gateway_dot_v1_dot_responses__pb2.ImageUploadValidateResponse.FromString,
            _registered_method=True,
        )
        self.ImageUploadConfirm = channel.unary_unary(
            "/gpcore.api.gateway.v1.GatewayService/ImageUploadConfirm",
            request_serializer=gpcore_dot_api_dot_gateway_dot_v1_dot_requests__pb2.ImageUploadConfirmRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_gateway_dot_v1_dot_responses__pb2.ImageUploadConfirmResponse.FromString,
            _registered_method=True,
        )


class GatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageUploadValidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ImageUploadConfirm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ImageUploadValidate": grpc.unary_unary_rpc_method_handler(
            servicer.ImageUploadValidate,
            request_deserializer=gpcore_dot_api_dot_gateway_dot_v1_dot_requests__pb2.ImageUploadValidateRequest.FromString,
            response_serializer=gpcore_dot_api_dot_gateway_dot_v1_dot_responses__pb2.ImageUploadValidateResponse.SerializeToString,
        ),
        "ImageUploadConfirm": grpc.unary_unary_rpc_method_handler(
            servicer.ImageUploadConfirm,
            request_deserializer=gpcore_dot_api_dot_gateway_dot_v1_dot_requests__pb2.ImageUploadConfirmRequest.FromString,
            response_serializer=gpcore_dot_api_dot_gateway_dot_v1_dot_responses__pb2.ImageUploadConfirmResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "gpcore.api.gateway.v1.GatewayService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "gpcore.api.gateway.v1.GatewayService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageUploadValidate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.gateway.v1.GatewayService/ImageUploadValidate",
            gpcore_dot_api_dot_gateway_dot_v1_dot_requests__pb2.ImageUploadValidateRequest.SerializeToString,
            gpcore_dot_api_dot_gateway_dot_v1_dot_responses__pb2.ImageUploadValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ImageUploadConfirm(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.gateway.v1.GatewayService/ImageUploadConfirm",
            gpcore_dot_api_dot_gateway_dot_v1_dot_requests__pb2.ImageUploadConfirmRequest.SerializeToString,
            gpcore_dot_api_dot_gateway_dot_v1_dot_responses__pb2.ImageUploadConfirmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
