# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/admin/v1/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/admin/v1/agent.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from gpcore_sdk.gpcore.api.cloud.v1 import (
    region_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_region__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgpcore/api/admin/v1/agent.proto\x12\x13gpcore.api.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a gpcore/api/cloud/v1/region.proto"[\n\x10\x41gentCertificate\x12\x1d\n\x15\x63\x65rtificate_authority\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x65rtificate\x18\x02 \x01(\t\x12\x13\n\x0bprivate_key\x18\x03 \x01(\t"\xd3\x01\n\x05\x41gent\x12\n\n\x02id\x18\x01 \x01(\t\x12,\n\x04type\x18\x02 \x01(\x0e\x32\x1e.gpcore.api.admin.v1.AgentType\x12\x33\n\ndatacenter\x18\x03 \x01(\x0b\x32\x1f.gpcore.api.cloud.v1.Datacenter\x12\x0c\n\x04\x66qdn\x18\x04 \x01(\t\x12\x17\n\x0fironic_endpoint\x18\x05 \x01(\t\x12\x34\n\x0flast_contact_at\x18\xe7\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*E\n\tAgentType\x12\x1a\n\x16\x41GENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x41GENT_TYPE_NETWORK_AGENT\x10\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.admin.v1.agent_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AGENTTYPE"]._serialized_start = 430
    _globals["_AGENTTYPE"]._serialized_end = 499
    _globals["_AGENTCERTIFICATE"]._serialized_start = 123
    _globals["_AGENTCERTIFICATE"]._serialized_end = 214
    _globals["_AGENT"]._serialized_start = 217
    _globals["_AGENT"]._serialized_end = 428
# @@protoc_insertion_point(module_scope)
