# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/admin/v1/arp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/admin/v1/arp.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dgpcore/api/admin/v1/arp.proto\x12\x13gpcore.api.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\xaf\x03\n\x08\x41RPEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bmac_address\x18\x04 \x01(\t\x12\x17\n\nmac_vendor\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x10netbox_switch_id\x18\x06 \x01(\x03\x12\x13\n\x0bswitch_port\x18\x07 \x01(\t\x12\x1d\n\x10netbox_device_id\x18\x08 \x01(\x03H\x01\x88\x01\x01\x12\x31\n\x0clast_seen_at\x18\xe6\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\x0clast_sync_at\x18\xe7\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\ncreated_at\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\nupdated_at\x18\xe9\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\ndeleted_at\x18\xea\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\r\n\x0b_mac_vendorB\x13\n\x11_netbox_device_idb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.admin.v1.arp_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ARPENTRY"]._serialized_start = 88
    _globals["_ARPENTRY"]._serialized_end = 519
# @@protoc_insertion_point(module_scope)
