# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/admin/v1/dashboard.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/admin/v1/dashboard.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.cloud.v1 import (
    flavour_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_flavour__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    server_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_server__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    region_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_region__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#gpcore/api/admin/v1/dashboard.proto\x12\x13gpcore.api.admin.v1\x1a!gpcore/api/cloud/v1/flavour.proto\x1a gpcore/api/cloud/v1/server.proto\x1a gpcore/api/cloud/v1/region.proto"d\n\x15\x44\x61shboardServerStatus\x12<\n\x06status\x18\x01 \x01(\x0e\x32,.gpcore.api.cloud.v1.ServerProvisioningState\x12\r\n\x05\x63ount\x18\x02 \x01(\x05"4\n\x10\x44\x61shboardIPStats\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x11\n\tavailable\x18\x02 \x01(\x05"i\n\x16\x44\x61shboardFlavourStatus\x12-\n\x07\x66lavour\x18\x01 \x01(\x0b\x32\x1c.gpcore.api.cloud.v1.Flavour\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x11\n\tavailable\x18\x03 \x01(\x05"\x89\x02\n\x11\x44\x61shboardLocation\x12\x33\n\ndatacenter\x18\x01 \x01(\x0b\x32\x1f.gpcore.api.cloud.v1.Datacenter\x12\x41\n\rserver_status\x18\x02 \x03(\x0b\x32*.gpcore.api.admin.v1.DashboardServerStatus\x12\x43\n\x0e\x66lavour_status\x18\x03 \x03(\x0b\x32+.gpcore.api.admin.v1.DashboardFlavourStatus\x12\x37\n\x08ip_stats\x18\x04 \x01(\x0b\x32%.gpcore.api.admin.v1.DashboardIPStats"F\n\tDashboard\x12\x39\n\tlocations\x18\x01 \x03(\x0b\x32&.gpcore.api.admin.v1.DashboardLocationb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.admin.v1.dashboard_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DASHBOARDSERVERSTATUS"]._serialized_start = 163
    _globals["_DASHBOARDSERVERSTATUS"]._serialized_end = 263
    _globals["_DASHBOARDIPSTATS"]._serialized_start = 265
    _globals["_DASHBOARDIPSTATS"]._serialized_end = 317
    _globals["_DASHBOARDFLAVOURSTATUS"]._serialized_start = 319
    _globals["_DASHBOARDFLAVOURSTATUS"]._serialized_end = 424
    _globals["_DASHBOARDLOCATION"]._serialized_start = 427
    _globals["_DASHBOARDLOCATION"]._serialized_end = 692
    _globals["_DASHBOARD"]._serialized_start = 694
    _globals["_DASHBOARD"]._serialized_end = 764
# @@protoc_insertion_point(module_scope)
