# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/admin/v1/flavour.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/admin/v1/flavour.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.cloud.v1 import (
    flavour_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_flavour__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!gpcore/api/admin/v1/flavour.proto\x12\x13gpcore.api.admin.v1\x1a!gpcore/api/cloud/v1/flavour.proto"\xe8\x01\n\x0c\x41\x64minFlavour\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x63pu\x18\x03 \x01(\t\x12\x12\n\ncpu_amount\x18\x04 \x01(\x05\x12\x11\n\tcpu_cores\x18\x05 \x01(\x05\x12\x13\n\x0b\x63pu_threads\x18\x06 \x01(\x05\x12\x0e\n\x06memory\x18\x07 \x01(\t\x12\x0c\n\x04\x64isk\x18\x08 \x01(\t\x12\x0f\n\x07network\x18\t \x01(\t\x12\x0f\n\x07traffic\x18\n \x01(\x03\x12\x35\n\x08mappings\x18\r \x03(\x0b\x32#.gpcore.api.cloud.v1.FlavourMappingb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.admin.v1.flavour_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ADMINFLAVOUR"]._serialized_start = 94
    _globals["_ADMINFLAVOUR"]._serialized_end = 326
# @@protoc_insertion_point(module_scope)
