# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/admin/v1/reporting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/admin/v1/reporting.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#gpcore/api/admin/v1/reporting.proto\x12\x13gpcore.api.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\x8d\x03\n\x13UsageReportingEntry\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x14\n\x0cproject_name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x18\n\x10\x64\x61tacenter_short\x18\x04 \x01(\t\x12\x14\n\x0c\x66lavour_name\x18\x05 \x01(\t\x12\x16\n\x0e\x62illing_period\x18\x06 \x01(\t\x12\x0f\n\x07user_id\x18\x07 \x01(\t\x12\x12\n\nuser_email\x18P \x01(\t\x12\x11\n\x04\x66qdn\x18\t \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06status\x18\n \x01(\t\x12\x16\n\x0e\x64uration_hours\x18\x0b \x01(\x01\x12\x14\n\x0cspla_license\x18\x0c \x01(\x08\x12/\n\ncreated_at\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\ndeleted_at\x18\xea\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x42\x07\n\x05_fqdnB\r\n\x0b_deleted_atb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.admin.v1.reporting_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USAGEREPORTINGENTRY"]._serialized_start = 94
    _globals["_USAGEREPORTINGENTRY"]._serialized_end = 491
# @@protoc_insertion_point(module_scope)
