# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/admin/v1/spla_reporting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "gpcore/api/admin/v1/spla_reporting.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.cloud.v1 import (
    server_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_server__pb2,
)
from gpcore_sdk.gpcore.type.v1 import price_pb2 as gpcore_dot_type_dot_v1_dot_price__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n(gpcore/api/admin/v1/spla_reporting.proto\x12\x13gpcore.api.admin.v1\x1a gpcore/api/cloud/v1/server.proto\x1a\x1agpcore/type/v1/price.proto"\xad\x01\n\rSplaReporting\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x06server\x18\x02 \x01(\x0b\x32\x1b.gpcore.api.cloud.v1.Server\x12$\n\x05price\x18\x03 \x01(\x0b\x32\x15.gpcore.type.v1.Price\x12\x12\n\ncpu_amount\x18\x04 \x01(\x05\x12\x11\n\tcpu_cores\x18\x05 \x01(\x05\x12\x16\n\x0epackage_amount\x18\x06 \x01(\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.admin.v1.spla_reporting_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SPLAREPORTING"]._serialized_start = 128
    _globals["_SPLAREPORTING"]._serialized_end = 301
# @@protoc_insertion_point(module_scope)
