# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/type/v1/audit_log.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/type/v1/audit_log.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1egpcore/type/v1/audit_log.proto\x12\x0egpcore.type.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\xc4\x01\n\rAuditLogToken\x12\x12\n\nsubject_id\x18\x01 \x01(\t\x12\x0e\n\x06jwt_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12.\n\nexpires_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tissued_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06issuer\x18\x06 \x01(\t\x12\x0c\n\x04type\x18\x07 \x01(\t"\xd9\x01\n\x08\x41uditLog\x12\x12\n\nrpc_method\x18\x01 \x01(\t\x12\x31\n\x05token\x18\x02 \x01(\x0b\x32\x1d.gpcore.type.v1.AuditLogTokenH\x00\x88\x01\x01\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x12\n\nuser_agent\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x12/\n\ncreated_at\x18\xe8\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\n\x06_tokenb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.type.v1.audit_log_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_AUDITLOGTOKEN"]._serialized_start = 84
    _globals["_AUDITLOGTOKEN"]._serialized_end = 280
    _globals["_AUDITLOG"]._serialized_start = 283
    _globals["_AUDITLOG"]._serialized_end = 500
# @@protoc_insertion_point(module_scope)
