# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/type/v1/cloud_provider.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/type/v1/cloud_provider.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n#gpcore/type/v1/cloud_provider.proto\x12\x0egpcore.type.v1*v\n\x11\x43loudProviderType\x12#\n\x1f\x43LOUD_PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x43LOUD_PROVIDER_TYPE_AWS\x10\x01\x12\x1f\n\x1b\x43LOUD_PROVIDER_TYPE_TENCENT\x10\x02\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.type.v1.cloud_provider_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CLOUDPROVIDERTYPE"]._serialized_start = 55
    _globals["_CLOUDPROVIDERTYPE"]._serialized_end = 173
# @@protoc_insertion_point(module_scope)
