# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/type/v1/credit_card.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/type/v1/credit_card.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n gpcore/type/v1/credit_card.proto\x12\x0egpcore.type.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\xc9\x01\n\nCreditCard\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rlast_4_digits\x18\x02 \x01(\t\x12,\n\x04type\x18\x03 \x01(\x0e\x32\x1e.gpcore.type.v1.CreditCardType\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12\r\n\x05valid\x18\x05 \x01(\x08\x12\x1a\n\x12supports_3d_secure\x18\x06 \x01(\x08\x12/\n\nexpires_at\x18\xe7\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xe4\x01\n\x0e\x43reditCardType\x12 \n\x1c\x43REDIT_CARD_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15\x43REDIT_CARD_TYPE_VISA\x10\x01\x12\x1f\n\x1b\x43REDIT_CARD_TYPE_MASTERCARD\x10\x02\x12\x19\n\x15\x43REDIT_CARD_TYPE_AMEX\x10\x03\x12\x1d\n\x19\x43REDIT_CARD_TYPE_DISCOVER\x10\x04\x12 \n\x1c\x43REDIT_CARD_TYPE_DINERS_CLUB\x10\x05\x12\x18\n\x14\x43REDIT_CARD_TYPE_JCB\x10\x06\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.type.v1.credit_card_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CREDITCARDTYPE"]._serialized_start = 290
    _globals["_CREDITCARDTYPE"]._serialized_end = 518
    _globals["_CREDITCARD"]._serialized_start = 86
    _globals["_CREDITCARD"]._serialized_end = 287
# @@protoc_insertion_point(module_scope)
