# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/type/v1/monitoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/type/v1/monitoring.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgpcore/type/v1/monitoring.proto\x12\x0egpcore.type.v1\x1a\x1fgoogle/protobuf/timestamp.proto"\xf2\x01\n\x0fMonitoringState\x12=\n\ncomponents\x18\x01 \x03(\x0b\x32).gpcore.type.v1.MonitoringState.Component\x12/\n\nupdated_at\x18\xe9\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1ao\n\tComponent\x12\x30\n\x06target\x18\x01 \x01(\x0e\x32 .gpcore.type.v1.MonitoringTarget\x12\x30\n\x0bheath_state\x18\x02 \x01(\x0e\x32\x1b.gpcore.type.v1.HealthState*u\n\x0bHealthState\x12\x1c\n\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x13\n\x0fHEALTH_STATE_OK\x10\x01\x12\x18\n\x14HEALTH_STATE_WARNING\x10\x02\x12\x19\n\x15HEALTH_STATE_CRITICAL\x10\x03*\xac\x01\n\x10MonitoringTarget\x12!\n\x1dMONITORING_TARGET_UNSPECIFIED\x10\x00\x12\x1d\n\x19MONITORING_TARGET_REDFISH\x10\x01\x12\x1c\n\x18MONITORING_TARGET_SYSTEM\x10\x02\x12\x1c\n\x18MONITORING_TARGET_MEMORY\x10\x03\x12\x1a\n\x16MONITORING_TARGET_DISK\x10\x04\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.type.v1.monitoring_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HEALTHSTATE"]._serialized_start = 329
    _globals["_HEALTHSTATE"]._serialized_end = 446
    _globals["_MONITORINGTARGET"]._serialized_start = 449
    _globals["_MONITORINGTARGET"]._serialized_end = 621
    _globals["_MONITORINGSTATE"]._serialized_start = 85
    _globals["_MONITORINGSTATE"]._serialized_end = 327
    _globals["_MONITORINGSTATE_COMPONENT"]._serialized_start = 216
    _globals["_MONITORINGSTATE_COMPONENT"]._serialized_end = 327
# @@protoc_insertion_point(module_scope)
