# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/type/v1/pagination.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/type/v1/pagination.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgpcore/type/v1/pagination.proto\x12\x0egpcore.type.v1"?\n\x11PaginationRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x12\n\x05limit\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\x08\n\x06_limit"@\n\x12PaginationResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05total\x18\x02 \x01(\x05\x12\r\n\x05limit\x18\x03 \x01(\x05\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.type.v1.pagination_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PAGINATIONREQUEST"]._serialized_start = 51
    _globals["_PAGINATIONREQUEST"]._serialized_end = 114
    _globals["_PAGINATIONRESPONSE"]._serialized_start = 116
    _globals["_PAGINATIONRESPONSE"]._serialized_end = 180
# @@protoc_insertion_point(module_scope)
