# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/type/v1/search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/type/v1/search.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1bgpcore/type/v1/search.proto\x12\x0egpcore.type.v1"\xca\x02\n\x0cSearchOption\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\x05label\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x01\x88\x01\x01\x12.\n\x04type\x18\x04 \x01(\x0e\x32 .gpcore.type.v1.SearchOptionType\x12\x1d\n\x10validation_regex\x18\x05 \x01(\tH\x02\x88\x01\x01\x12I\n\x0f\x64ropdown_values\x18\x06 \x03(\x0b\x32\x30.gpcore.type.v1.SearchOption.DropdownValuesEntry\x1a\x35\n\x13\x44ropdownValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_labelB\x0e\n\x0c_descriptionB\x13\n\x11_validation_regex">\n\rSearchOptions\x12-\n\x07options\x18\x01 \x03(\x0b\x32\x1c.gpcore.type.v1.SearchOption"i\n\x06\x46ilter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0cstring_value\x18\x02 \x01(\tH\x00\x12\x17\n\rinteger_value\x18\x03 \x01(\x03H\x00\x12\x17\n\rboolean_value\x18\x04 \x01(\x08H\x00\x42\x07\n\x05value"8\n\rSearchRequest\x12\'\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x16.gpcore.type.v1.Filter*\xb6\x01\n\x10SearchOptionType\x12"\n\x1eSEARCH_OPTION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n\x19SEARCH_OPTION_TYPE_STRING\x10\x01\x12\x1e\n\x1aSEARCH_OPTION_TYPE_INTEGER\x10\x02\x12\x1f\n\x1bSEARCH_OPTION_TYPE_DROPDOWN\x10\x03\x12\x1e\n\x1aSEARCH_OPTION_TYPE_BOOLEAN\x10\x04\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.type.v1.search_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SEARCHOPTION_DROPDOWNVALUESENTRY"]._loaded_options = None
    _globals["_SEARCHOPTION_DROPDOWNVALUESENTRY"]._serialized_options = b"8\001"
    _globals["_SEARCHOPTIONTYPE"]._serialized_start = 610
    _globals["_SEARCHOPTIONTYPE"]._serialized_end = 792
    _globals["_SEARCHOPTION"]._serialized_start = 48
    _globals["_SEARCHOPTION"]._serialized_end = 378
    _globals["_SEARCHOPTION_DROPDOWNVALUESENTRY"]._serialized_start = 278
    _globals["_SEARCHOPTION_DROPDOWNVALUESENTRY"]._serialized_end = 331
    _globals["_SEARCHOPTIONS"]._serialized_start = 380
    _globals["_SEARCHOPTIONS"]._serialized_end = 442
    _globals["_FILTER"]._serialized_start = 444
    _globals["_FILTER"]._serialized_end = 549
    _globals["_SEARCHREQUEST"]._serialized_start = 551
    _globals["_SEARCHREQUEST"]._serialized_end = 607
# @@protoc_insertion_point(module_scope)
