# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/type/v1/ssh_key.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/type/v1/ssh_key.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cgpcore/type/v1/ssh_key.proto\x12\x0egpcore.type.v1"\x8a\x01\n\x06SSHKey\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12(\n\x04type\x18\x03 \x01(\x0e\x32\x1a.gpcore.type.v1.SSHKeyType\x12\x12\n\npublic_key\x18\x04 \x01(\t\x12\x18\n\x0b\x66ingerprint\x18\x05 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_fingerprint*\x88\x01\n\nSSHKeyType\x12\x1c\n\x18SSH_KEY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10SSH_KEY_TYPE_RSA\x10\x01\x12\x14\n\x10SSH_KEY_TYPE_DSA\x10\x02\x12\x16\n\x12SSH_KEY_TYPE_ECDSA\x10\x03\x12\x18\n\x14SSH_KEY_TYPE_ED25519\x10\x04\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.type.v1.ssh_key_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SSHKEYTYPE"]._serialized_start = 190
    _globals["_SSHKEYTYPE"]._serialized_end = 326
    _globals["_SSHKEY"]._serialized_start = 49
    _globals["_SSHKEY"]._serialized_end = 187
# @@protoc_insertion_point(module_scope)
