# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v2/requests.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v2/requests.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.type.v1 import (
    pagination_pb2 as gpcore_dot_type_dot_v1_dot_pagination__pb2,
)
from gpcore_sdk.gpcore.type.v1 import (
    search_pb2 as gpcore_dot_type_dot_v1_dot_search__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"gpcore/api/cloud/v2/requests.proto\x12\x13gpcore.api.cloud.v2\x1a\x1fgpcore/type/v1/pagination.proto\x1a\x1bgpcore/type/v1/search.proto"\x93\x01\n\x1eListBillingProfileBillsRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12:\n\npagination\x18\x02 \x01(\x0b\x32!.gpcore.type.v1.PaginationRequestH\x00\x88\x01\x01\x12\x11\n\x04year\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\r\n\x0b_paginationB\x07\n\x05_year"z\n!ListBillingProfileProjectsRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12:\n\npagination\x18\x02 \x01(\x0b\x32!.gpcore.type.v1.PaginationRequestH\x00\x88\x01\x01\x42\r\n\x0b_pagination"\x90\x01\n\x16ListProjectLogsRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12:\n\npagination\x18\x02 \x01(\x0b\x32!.gpcore.type.v1.PaginationRequestH\x00\x88\x01\x01\x12\x0e\n\x06search\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\tB\r\n\x0b_pagination"\xda\x01\n\x10ListNodesRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12:\n\npagination\x18\x02 \x01(\x0b\x32!.gpcore.type.v1.PaginationRequestH\x00\x88\x01\x01\x12\x13\n\x06search\x18\x03 \x01(\tH\x01\x88\x01\x01\x12;\n\x0f\x65xtended_search\x18\x04 \x01(\x0b\x32\x1d.gpcore.type.v1.SearchRequestH\x02\x88\x01\x01\x42\r\n\x0b_paginationB\t\n\x07_searchB\x12\n\x10_extended_search"\x17\n\x15ReadinessCheckRequestb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v2.requests_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LISTBILLINGPROFILEBILLSREQUEST"]._serialized_start = 122
    _globals["_LISTBILLINGPROFILEBILLSREQUEST"]._serialized_end = 269
    _globals["_LISTBILLINGPROFILEPROJECTSREQUEST"]._serialized_start = 271
    _globals["_LISTBILLINGPROFILEPROJECTSREQUEST"]._serialized_end = 393
    _globals["_LISTPROJECTLOGSREQUEST"]._serialized_start = 396
    _globals["_LISTPROJECTLOGSREQUEST"]._serialized_end = 540
    _globals["_LISTNODESREQUEST"]._serialized_start = 543
    _globals["_LISTNODESREQUEST"]._serialized_end = 761
    _globals["_READINESSCHECKREQUEST"]._serialized_start = 763
    _globals["_READINESSCHECKREQUEST"]._serialized_end = 786
# @@protoc_insertion_point(module_scope)
