# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v2/responses.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v2/responses.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.cloud.v1 import (
    project_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_project__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    billing_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_billing__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    node_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_node__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v1 import (
    user_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_user__pb2,
)
from gpcore_sdk.gpcore.type.v1 import (
    pagination_pb2 as gpcore_dot_type_dot_v1_dot_pagination__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#gpcore/api/cloud/v2/responses.proto\x12\x13gpcore.api.cloud.v2\x1a!gpcore/api/cloud/v1/project.proto\x1a!gpcore/api/cloud/v1/billing.proto\x1a\x1egpcore/api/cloud/v1/node.proto\x1a\x1egpcore/api/cloud/v1/user.proto\x1a\x1fgpcore/type/v1/pagination.proto"\xb5\x01\n\x1fListBillingProfileBillsResponse\x12(\n\x05\x62ills\x18\x01 \x03(\x0b\x32\x19.gpcore.api.cloud.v1.Bill\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05years\x18\x03 \x03(\x05\x12\r\n\x05total\x18\x04 \x01(\x03\x42\r\n\x0b_pagination"\xb4\x01\n"ListBillingProfileProjectsResponse\x12\x33\n\x08projects\x18\x01 \x03(\x0b\x32!.gpcore.api.cloud.v1.BasicProject\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05total\x18\x03 \x01(\x03\x42\r\n\x0b_pagination"\xd2\x01\n\x17ListProjectLogsResponse\x12-\n\x04logs\x18\x01 \x03(\x0b\x32\x1f.gpcore.api.cloud.v1.ProjectLog\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05total\x18\x03 \x01(\x03\x12-\n\x05users\x18\x04 \x03(\x0b\x32\x1e.gpcore.api.cloud.v1.BasicUserB\r\n\x0b_pagination"\x98\x01\n\x11ListNodesResponse\x12(\n\x05nodes\x18\x01 \x03(\x0b\x32\x19.gpcore.api.cloud.v1.Node\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05total\x18\x03 \x01(\x03\x42\r\n\x0b_pagination")\n\x16ReadinessCheckResponse\x12\x0f\n\x07version\x18\x01 \x01(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v2.responses_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_LISTBILLINGPROFILEBILLSRESPONSE"]._serialized_start = 228
    _globals["_LISTBILLINGPROFILEBILLSRESPONSE"]._serialized_end = 409
    _globals["_LISTBILLINGPROFILEPROJECTSRESPONSE"]._serialized_start = 412
    _globals["_LISTBILLINGPROFILEPROJECTSRESPONSE"]._serialized_end = 592
    _globals["_LISTPROJECTLOGSRESPONSE"]._serialized_start = 595
    _globals["_LISTPROJECTLOGSRESPONSE"]._serialized_end = 805
    _globals["_LISTNODESRESPONSE"]._serialized_start = 808
    _globals["_LISTNODESRESPONSE"]._serialized_end = 960
    _globals["_READINESSCHECKRESPONSE"]._serialized_start = 962
    _globals["_READINESSCHECKRESPONSE"]._serialized_end = 1003
# @@protoc_insertion_point(module_scope)
