# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/cloud/v2/rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/cloud/v2/rpc.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.v1 import options_pb2 as gpcore_dot_v1_dot_options__pb2
from gpcore_sdk.gpcore.api.cloud.v2 import (
    requests_pb2 as gpcore_dot_api_dot_cloud_dot_v2_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.cloud.v2 import (
    responses_pb2 as gpcore_dot_api_dot_cloud_dot_v2_dot_responses__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1dgpcore/api/cloud/v2/rpc.proto\x12\x13gpcore.api.cloud.v2\x1a\x17gpcore/v1/options.proto\x1a"gpcore/api/cloud/v2/requests.proto\x1a#gpcore/api/cloud/v2/responses.proto2\xe9\x04\n\x0c\x43loudService\x12\x86\x01\n\x17ListBillingProfileBills\x12\x33.gpcore.api.cloud.v2.ListBillingProfileBillsRequest\x1a\x34.gpcore.api.cloud.v2.ListBillingProfileBillsResponse"\x00\x12\x8f\x01\n\x1aListBillingProfileProjects\x12\x36.gpcore.api.cloud.v2.ListBillingProfileProjectsRequest\x1a\x37.gpcore.api.cloud.v2.ListBillingProfileProjectsResponse"\x00\x12n\n\x0fListProjectLogs\x12+.gpcore.api.cloud.v2.ListProjectLogsRequest\x1a,.gpcore.api.cloud.v2.ListProjectLogsResponse"\x00\x12\\\n\tListNodes\x12%.gpcore.api.cloud.v2.ListNodesRequest\x1a&.gpcore.api.cloud.v2.ListNodesResponse"\x00\x12p\n\x0eReadinessCheck\x12*.gpcore.api.cloud.v2.ReadinessCheckRequest\x1a+.gpcore.api.cloud.v2.ReadinessCheckResponse"\x05\xe2\x44\x02\x08\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.cloud.v2.rpc_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CLOUDSERVICE"].methods_by_name["ReadinessCheck"]._loaded_options = None
    _globals["_CLOUDSERVICE"].methods_by_name[
        "ReadinessCheck"
    ]._serialized_options = b"\342D\002\010\001"
    _globals["_CLOUDSERVICE"]._serialized_start = 153
    _globals["_CLOUDSERVICE"]._serialized_end = 770
# @@protoc_insertion_point(module_scope)
