# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/network/v1/requests.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/network/v1/requests.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from gpcore_sdk.gpcore.api.cloud.v1 import (
    monitoring_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_monitoring__pb2,
)
from gpcore_sdk.gpcore.type.v1 import (
    pagination_pb2 as gpcore_dot_type_dot_v1_dot_pagination__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n$gpcore/api/network/v1/requests.proto\x12\x15gpcore.api.network.v1\x1a\x1b\x62uf/validate/validate.proto\x1a$gpcore/api/cloud/v1/monitoring.proto\x1a\x1fgpcore/type/v1/pagination.proto"0\n\x19GetDHCPInformationRequest\x12\x13\n\x0bmac_address\x18\x01 \x01(\t"i\n\x1cListMonitoringTargetsRequest\x12:\n\npagination\x18\x01 \x01(\x0b\x32!.gpcore.type.v1.PaginationRequestH\x00\x88\x01\x01\x42\r\n\x0b_pagination"V\n\x1dUpdateMonitoringStatusRequest\x12\x35\n\x06status\x18\x01 \x03(\x0b\x32%.gpcore.api.cloud.v1.MonitoringStatus"\x1a\n\x18GetArpInformationRequest"U\n\x16NotifyArpChangeRequest\x12\x1e\n\x0bmac_address\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x0c\x18\x11\x12\x1b\n\nip_address\x18\x02 \x01(\tB\x07\xbaH\x04r\x02p\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.network.v1.requests_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NOTIFYARPCHANGEREQUEST"].fields_by_name[
        "mac_address"
    ]._loaded_options = None
    _globals["_NOTIFYARPCHANGEREQUEST"].fields_by_name[
        "mac_address"
    ]._serialized_options = b"\272H\006r\004\020\014\030\021"
    _globals["_NOTIFYARPCHANGEREQUEST"].fields_by_name[
        "ip_address"
    ]._loaded_options = None
    _globals["_NOTIFYARPCHANGEREQUEST"].fields_by_name[
        "ip_address"
    ]._serialized_options = b"\272H\004r\002p\001"
    _globals["_GETDHCPINFORMATIONREQUEST"]._serialized_start = 163
    _globals["_GETDHCPINFORMATIONREQUEST"]._serialized_end = 211
    _globals["_LISTMONITORINGTARGETSREQUEST"]._serialized_start = 213
    _globals["_LISTMONITORINGTARGETSREQUEST"]._serialized_end = 318
    _globals["_UPDATEMONITORINGSTATUSREQUEST"]._serialized_start = 320
    _globals["_UPDATEMONITORINGSTATUSREQUEST"]._serialized_end = 406
    _globals["_GETARPINFORMATIONREQUEST"]._serialized_start = 408
    _globals["_GETARPINFORMATIONREQUEST"]._serialized_end = 434
    _globals["_NOTIFYARPCHANGEREQUEST"]._serialized_start = 436
    _globals["_NOTIFYARPCHANGEREQUEST"]._serialized_end = 521
# @@protoc_insertion_point(module_scope)
