# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/network/v1/responses.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "gpcore/api/network/v1/responses.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.api.cloud.v1 import (
    monitoring_pb2 as gpcore_dot_api_dot_cloud_dot_v1_dot_monitoring__pb2,
)
from gpcore_sdk.gpcore.api.admin.v1 import (
    arp_ip_history_pb2 as gpcore_dot_api_dot_admin_dot_v1_dot_arp__ip__history__pb2,
)
from gpcore_sdk.gpcore.type.v1 import (
    pagination_pb2 as gpcore_dot_type_dot_v1_dot_pagination__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%gpcore/api/network/v1/responses.proto\x12\x15gpcore.api.network.v1\x1a$gpcore/api/cloud/v1/monitoring.proto\x1a(gpcore/api/admin/v1/arp_ip_history.proto\x1a\x1fgpcore/type/v1/pagination.proto"~\n\x1aGetDHCPInformationResponse\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0f\n\x07gateway\x18\x02 \x01(\t\x12\x13\n\x0b\x64ns_servers\x18\x03 \x03(\t\x12\x13\n\x0bntp_servers\x18\x04 \x03(\t\x12\x11\n\tlease_ttl\x18\x05 \x01(\t"\xb2\x01\n\x1dListMonitoringTargetsResponse\x12\x36\n\x07targets\x18\x01 \x03(\x0b\x32%.gpcore.api.cloud.v1.MonitoringTarget\x12;\n\npagination\x18\x02 \x01(\x0b\x32".gpcore.type.v1.PaginationResponseH\x00\x88\x01\x01\x12\r\n\x05total\x18\x03 \x01(\x03\x42\r\n\x0b_pagination" \n\x1eUpdateMonitoringStatusResponse"\xb1\x01\n\x19GetArpInformationResponse\x12\x10\n\x08networks\x18\x01 \x03(\t\x12Q\n\tarp_table\x18\x02 \x03(\x0b\x32>.gpcore.api.network.v1.GetArpInformationResponse.ArpTableEntry\x1a/\n\rArpTableEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01"T\n\x17NotifyArpChangeResponse\x12\x39\n\x0e\x61rp_ip_history\x18\x01 \x01(\x0b\x32!.gpcore.api.admin.v1.ArpIpHistoryb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.network.v1.responses_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETARPINFORMATIONRESPONSE_ARPTABLEENTRY"]._loaded_options = None
    _globals["_GETARPINFORMATIONRESPONSE_ARPTABLEENTRY"]._serialized_options = b"8\001"
    _globals["_GETDHCPINFORMATIONRESPONSE"]._serialized_start = 177
    _globals["_GETDHCPINFORMATIONRESPONSE"]._serialized_end = 303
    _globals["_LISTMONITORINGTARGETSRESPONSE"]._serialized_start = 306
    _globals["_LISTMONITORINGTARGETSRESPONSE"]._serialized_end = 484
    _globals["_UPDATEMONITORINGSTATUSRESPONSE"]._serialized_start = 486
    _globals["_UPDATEMONITORINGSTATUSRESPONSE"]._serialized_end = 518
    _globals["_GETARPINFORMATIONRESPONSE"]._serialized_start = 521
    _globals["_GETARPINFORMATIONRESPONSE"]._serialized_end = 698
    _globals["_GETARPINFORMATIONRESPONSE_ARPTABLEENTRY"]._serialized_start = 651
    _globals["_GETARPINFORMATIONRESPONSE_ARPTABLEENTRY"]._serialized_end = 698
    _globals["_NOTIFYARPCHANGERESPONSE"]._serialized_start = 700
    _globals["_NOTIFYARPCHANGERESPONSE"]._serialized_end = 784
# @@protoc_insertion_point(module_scope)
