# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpcore/api/network/v1/rpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gpcore/api/network/v1/rpc.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gpcore_sdk.gpcore.v1 import options_pb2 as gpcore_dot_v1_dot_options__pb2
from gpcore_sdk.gpcore.api.network.v1 import (
    requests_pb2 as gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.network.v1 import (
    responses_pb2 as gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1fgpcore/api/network/v1/rpc.proto\x12\x15gpcore.api.network.v1\x1a\x17gpcore/v1/options.proto\x1a$gpcore/api/network/v1/requests.proto\x1a%gpcore/api/network/v1/responses.proto2\xa6\x05\n\x0eNetworkService\x12\x80\x01\n\x12GetDHCPInformation\x12\x30.gpcore.api.network.v1.GetDHCPInformationRequest\x1a\x31.gpcore.api.network.v1.GetDHCPInformationResponse"\x05\xe2\x44\x02\x08\x03\x12\x89\x01\n\x15ListMonitoringTargets\x12\x33.gpcore.api.network.v1.ListMonitoringTargetsRequest\x1a\x34.gpcore.api.network.v1.ListMonitoringTargetsResponse"\x05\xe2\x44\x02\x08\x03\x12\x8c\x01\n\x16UpdateMonitoringStatus\x12\x34.gpcore.api.network.v1.UpdateMonitoringStatusRequest\x1a\x35.gpcore.api.network.v1.UpdateMonitoringStatusResponse"\x05\xe2\x44\x02\x08\x03\x12}\n\x11GetArpInformation\x12/.gpcore.api.network.v1.GetArpInformationRequest\x1a\x30.gpcore.api.network.v1.GetArpInformationResponse"\x05\xe2\x44\x02\x08\x03\x12w\n\x0fNotifyArpChange\x12-.gpcore.api.network.v1.NotifyArpChangeRequest\x1a..gpcore.api.network.v1.NotifyArpChangeResponse"\x05\xe2\x44\x02\x08\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "gpcore.api.network.v1.rpc_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NETWORKSERVICE"].methods_by_name[
        "GetDHCPInformation"
    ]._loaded_options = None
    _globals["_NETWORKSERVICE"].methods_by_name[
        "GetDHCPInformation"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_NETWORKSERVICE"].methods_by_name[
        "ListMonitoringTargets"
    ]._loaded_options = None
    _globals["_NETWORKSERVICE"].methods_by_name[
        "ListMonitoringTargets"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_NETWORKSERVICE"].methods_by_name[
        "UpdateMonitoringStatus"
    ]._loaded_options = None
    _globals["_NETWORKSERVICE"].methods_by_name[
        "UpdateMonitoringStatus"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_NETWORKSERVICE"].methods_by_name[
        "GetArpInformation"
    ]._loaded_options = None
    _globals["_NETWORKSERVICE"].methods_by_name[
        "GetArpInformation"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_NETWORKSERVICE"].methods_by_name[
        "NotifyArpChange"
    ]._loaded_options = None
    _globals["_NETWORKSERVICE"].methods_by_name[
        "NotifyArpChange"
    ]._serialized_options = b"\342D\002\010\003"
    _globals["_NETWORKSERVICE"]._serialized_start = 161
    _globals["_NETWORKSERVICE"]._serialized_end = 839
# @@protoc_insertion_point(module_scope)
