# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from gpcore_sdk.gpcore.api.network.v1 import (
    requests_pb2 as gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2,
)
from gpcore_sdk.gpcore.api.network.v1 import (
    responses_pb2 as gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2,
)

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in gpcore/api/network/v1/rpc_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NetworkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDHCPInformation = channel.unary_unary(
            "/gpcore.api.network.v1.NetworkService/GetDHCPInformation",
            request_serializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.GetDHCPInformationRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.GetDHCPInformationResponse.FromString,
            _registered_method=True,
        )
        self.ListMonitoringTargets = channel.unary_unary(
            "/gpcore.api.network.v1.NetworkService/ListMonitoringTargets",
            request_serializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.ListMonitoringTargetsRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.ListMonitoringTargetsResponse.FromString,
            _registered_method=True,
        )
        self.UpdateMonitoringStatus = channel.unary_unary(
            "/gpcore.api.network.v1.NetworkService/UpdateMonitoringStatus",
            request_serializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.UpdateMonitoringStatusRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.UpdateMonitoringStatusResponse.FromString,
            _registered_method=True,
        )
        self.GetArpInformation = channel.unary_unary(
            "/gpcore.api.network.v1.NetworkService/GetArpInformation",
            request_serializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.GetArpInformationRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.GetArpInformationResponse.FromString,
            _registered_method=True,
        )
        self.NotifyArpChange = channel.unary_unary(
            "/gpcore.api.network.v1.NetworkService/NotifyArpChange",
            request_serializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.NotifyArpChangeRequest.SerializeToString,
            response_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.NotifyArpChangeResponse.FromString,
            _registered_method=True,
        )


class NetworkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDHCPInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMonitoringTargets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateMonitoringStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetArpInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def NotifyArpChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NetworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetDHCPInformation": grpc.unary_unary_rpc_method_handler(
            servicer.GetDHCPInformation,
            request_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.GetDHCPInformationRequest.FromString,
            response_serializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.GetDHCPInformationResponse.SerializeToString,
        ),
        "ListMonitoringTargets": grpc.unary_unary_rpc_method_handler(
            servicer.ListMonitoringTargets,
            request_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.ListMonitoringTargetsRequest.FromString,
            response_serializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.ListMonitoringTargetsResponse.SerializeToString,
        ),
        "UpdateMonitoringStatus": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateMonitoringStatus,
            request_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.UpdateMonitoringStatusRequest.FromString,
            response_serializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.UpdateMonitoringStatusResponse.SerializeToString,
        ),
        "GetArpInformation": grpc.unary_unary_rpc_method_handler(
            servicer.GetArpInformation,
            request_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.GetArpInformationRequest.FromString,
            response_serializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.GetArpInformationResponse.SerializeToString,
        ),
        "NotifyArpChange": grpc.unary_unary_rpc_method_handler(
            servicer.NotifyArpChange,
            request_deserializer=gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.NotifyArpChangeRequest.FromString,
            response_serializer=gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.NotifyArpChangeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "gpcore.api.network.v1.NetworkService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "gpcore.api.network.v1.NetworkService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class NetworkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDHCPInformation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.network.v1.NetworkService/GetDHCPInformation",
            gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.GetDHCPInformationRequest.SerializeToString,
            gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.GetDHCPInformationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMonitoringTargets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.network.v1.NetworkService/ListMonitoringTargets",
            gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.ListMonitoringTargetsRequest.SerializeToString,
            gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.ListMonitoringTargetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateMonitoringStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.network.v1.NetworkService/UpdateMonitoringStatus",
            gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.UpdateMonitoringStatusRequest.SerializeToString,
            gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.UpdateMonitoringStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetArpInformation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.network.v1.NetworkService/GetArpInformation",
            gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.GetArpInformationRequest.SerializeToString,
            gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.GetArpInformationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def NotifyArpChange(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gpcore.api.network.v1.NetworkService/NotifyArpChange",
            gpcore_dot_api_dot_network_dot_v1_dot_requests__pb2.NotifyArpChangeRequest.SerializeToString,
            gpcore_dot_api_dot_network_dot_v1_dot_responses__pb2.NotifyArpChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
